# Generated by Django 4.2.7 on 2023-11-26 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pub_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                ("genre", models.CharField(max_length=128, verbose_name="Жанр")),
                ("published", models.DateField(verbose_name="Дата издания")),
                (
                    "isbn",
                    models.CharField(
                        max_length=17, verbose_name="ISBN в формате xxx-x-xxxx-xxxx-x"
                    ),
                ),
                ("authors", models.ManyToManyField(to="pub_system.author")),
            ],
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
            ],
        ),
        migrations.AddField(
            model_name="publishing",
            name="additional_info",
            field=models.TextField(default=1, verbose_name="Доп. информация"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publishing",
            name="address",
            field=models.CharField(
                default=datetime.datetime(2023, 11, 26, 15, 43, 16, 139144),
                max_length=256,
                verbose_name="Название",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publishing",
            name="created",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 26, 15, 43, 21, 64868),
                verbose_name="Дата основания",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count_sales",
                    models.IntegerField(verbose_name="Число проданных экземпляров"),
                ),
                (
                    "sale_price",
                    models.IntegerField(verbose_name="Цена за проданный экземпляр"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pub_system.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="editor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pub_system.editor",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="published_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pub_system.publishing",
            ),
        ),
        migrations.AddField(
            model_name="publishing",
            name="authors",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pub_system.author",
            ),
        ),
        migrations.AddField(
            model_name="publishing",
            name="editors",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pub_system.editor",
            ),
        ),
    ]
