# Generated by Django 4.2.7 on 2023-12-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub_system", "0002_author_book_editor_publishing_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishing",
            name="address",
            field=models.CharField(max_length=256, verbose_name="Адрес"),
        ),
        migrations.RemoveField(
            model_name="publishing",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="publishing",
            name="editors",
        ),
        migrations.AddField(
            model_name="publishing",
            name="authors",
            field=models.ManyToManyField(null=True, to="pub_system.author"),
        ),
        migrations.AddField(
            model_name="publishing",
            name="editors",
            field=models.ManyToManyField(null=True, to="pub_system.editor"),
        ),
    ]
