# Generated by Django 4.2.7 on 2023-12-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pub_system",
            "0003_alter_publishing_address_remove_publishing_authors_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publishing",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Действующее"),
        ),
    ]
